hotkeys:
  record: ["f"]
  # record: ["Button.x1"]
  exit: ["Key.ctrl_l", "q"]

device: 1
model: "openai/whisper-base"
key_during_tts: "l"

local: true

voice_profile: "nova"
# voice_profile: "ash"
# Matilda
elabs_voice_id: "XrExE9yKIg1WjnnlVkGX"